export const ACTION_TYPES = {
    //Products
    SET_PRODUCT: "SET_PRODUCT",
    GET_PRODUCTS: "GET_PRODUCTS",
    DELETE_PRODUCTS: "DELETE_PRODUCTS",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",

    //Teacherss
    SET_TEACHER: "SET_TEACHER",
    GET_TEACHERS: "GET_TEACHERS",
    DELETE_TEACHERS: "DELETE_TEACHERS",
    UPDATE_TEACHERS: "UPDATE_TEACHERS",

    //Categories
    SET_CATEGORY: "SET_PRODUCT",
    GET_CATEGORIES: "GET_CATEGORIES",
    DELETE_CATEGORIES: "DELETE_CATEGORIES",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",

    //Useful-Tips
    SET_USEFUL_TIPS: "SET_USEFUL_TIPS",
    GET_USEFUL_TIPS_ICON: "GET_USEFUL_TIPS_ICON",
    GET_USEFUL_TIPS: "GET_USEFUL_TIPS",
    DELETE_USEFUL_TIP: "DELETE_USEFUL_TIP",
    UPDATE_USEFUL_TIP: "UPDATE_USEFUL_TIP",


    //Videos
    SET_VIDEO: "SSET_VIDEO",
    GET_VIDEOS: "GET_VIDEOS",
    DELETE_VIDEOS: "DELETE_VIDEOS",
    UPDATE_VIDEO: "UPDATE_VIDEO",


    //Questions
    ADD_CATEGORY_QUESTIONS : "ADD_CATEGORY_QUESTIONS",
    ADD_PERSIAN_CATEGORY_QUESTIONS : "ADD_PERSIAN_CATEGORY_QUESTIONS",
    UPDATE_CATEGORY_QUESTIONS : "UPDATE_CATEGORY_QUESTIONS",
    DELETE_CATEGORY_QUESTIONS : "DELETE_CATEGORY_QUESTIONS",
    GET_ENG_CATEGORY_QUESTIONS : "GET_ENG_CATEGORY_QUESTIONS",
    GET_PER_CATEGORY_QUESTIONS : "GET_PER_CATEGORY_QUESTIONS",

    //Answers
    GET_ALL_DEVICES_DATA : "GET_ALL_DEVICES_DATA",


    //Test-Questions
    ADD_TEST_CATEGORY_QUESTIONS : "ADD_TEST_CATEGORY_QUESTIONS",
    ADD_TEST_PERSIAN_CATEGORY_QUESTIONS : "ADD_TEST_PERSIAN_CATEGORY_QUESTIONS",
    UPDATE_TEST_CATEGORY_QUESTIONS : "UPDATE_TEST_CATEGORY_QUESTIONS",
    DELETE_TEST_CATEGORY_QUESTIONS : "DELETE_TEST_CATEGORY_QUESTIONS",
    GET_TEST_ENG_CATEGORY_QUESTIONS : "GET_TEST_ENG_CATEGORY_QUESTIONS",
    GET_TEST_PER_CATEGORY_QUESTIONS : "GET_TEST_PER_CATEGORY_QUESTIONS",

    //drivers
    GET_UNAPPROVED_DRIVERS: "GET_UNAPPROVED_DRIVERS",
    UPDATE_DRIVER_STATUS: "UPDATE_DRIVER_STATUS",

    //Orders
    GET_ORDER_BY_ID: "GET_ORDER_BY_ID",
    
    //Users
    GET_UNAPPROVED_USERS: "GET_UNAPPROVED_USERS",
    GET_DEACTIVATE_USERS: "GET_DEACTIVATE_USERS",
    UPDATE_USER_STATUS: "UPDATE_USER_STATUS",

    //Blogs
    SET_BLOG: "SET_BLOG",
    GET_BLOGS: "GET_BLOGS",
    GET_SINGLE_BLOG: "GET_SINGLE_BLOG",
    DELETE_BLOG: "DELETE_BLOG",
    UPDATE_BLOG: "UPDATE_BLOG",

    //Banner
    SET_BANNER: "SET_BANNER",
    GET_BANNER: "GET_BANNER",
    GET_SINGLE_BANNER: "GET_SINGLE_BANNER",
    DELETE_BANNER: "DELETE_BANNER",
    UPDATE_BANNER: "UPDATE_BANNER",

    //progress
    PROGRESS_BAR_STATE: "PROGRESS_BAR_STATE",

    //login
    LOGIN: "LOGIN"
}